### ISSUE TITLE
color and title of the label are lost

### ISSUE THREAD

**Issue by MemePortela** [micz/ColumnsWizard#65] opened 2017-09-18 09:11 UTC
When a change is made to a column, the color and title of the label are lost.

**Comment by micz** [comment] 2018-02-05 22:00
May you post here or send to m@micz.it a few screenshot describing the problem?
Please also add info about the Thunderbird version and your Operating System, thank you.

**Comment by MemePortela** [comment] 2018-02-06 10:13
![ashampoo_snap_2018 02 06_08h31m59s_002_](https://user-images.githubusercontent.com/32059442/35853748-4f74f382-0b26-11e8-8f86-1b0fe3294073.png)
![ashampoo_snap_2018 02 06_08h26m13s_001_](https://user-images.githubusercontent.com/32059442/35853750-4f9569be-0b26-11e8-8c7f-e6eeb4d578a8.png)

**Comment by micz** [comment] 2018-02-06 23:03
Are you using an IMAP account?
I tried it on Gmail via IMAP and the tags are kept, so the labels and colors are still there after the modification.

**Comment by MemePortela** [comment] 2018-02-07 03:42
Yes IMAP but not gmail. Thunderbird

Meme Portela
Enviado desde mi iPhone

**Comment by micz** [comment] 2018-02-08 06:49
May you check on your webmail if you see yours tags/labels present in Thunderbird?

Maybe the problem is that Gmail IMAP (and also Zimbra) stores the tags/labels on the server, but other IMAP servers don't, so I need a way to keep track of them on the client side.
Thank you.

**Comment by MemePortela** [comment] 2018-02-08 12:46
I think that's exactly what happens.

Thank you very much!!!

2018-02-08 6:49 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-09 22:57
Please try version 6.1alpha3 from here: https://addons.mozilla.org/it/thunderbird/addon/columnswizard/versions/beta

**Comment by MemePortela** [comment] 2018-02-12 09:17
Don't work for my version of Thunderbird Version 52.6.0

2018-02-09 22:57 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-12 21:26
I mistyped a reference, sorry.
Please try version 6.1alpha5 from the beta channel. Thank you.

**Comment by MemePortela** [comment] 2018-02-14 08:36
Its the same. lost label and colour

Thanks
Regards

2018-02-12 21:26 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-15 22:13
If possible, I need your help, since that version works fine in my test environment.
I've released version 6.1alpha6 that adds some useful logs.

You need to activate the debug system from the advanced tab in the preference, here:

![image](https://user-images.githubusercontent.com/61795/36283600-4db93036-12a5-11e8-96e5-ee443d93d60b.png)

After that, please, change the header in one mail and send me the logs you could find in the error console, that you could open using CRTL+SHIFT+J.

They should be something like that:

```
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: $label2 nonjunk
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: $label2,nonjunk
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: $label2 nonjunk
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: $label2,nonjunk
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags: $label2,nonjunk
ColumnsWizard >>> 23:0:4.378
miczColumnsWizard_MsgUtils.postActions miczColumnsWizard_MsgUtils.tags: $label2 nonjunk
```

Thank you!

**Comment by MemePortela** [comment] 2018-02-16 08:59
Se esperaba una declaración, pero se encontró '!'.  Ignorado hasta la
siguiente declaración.  quicknote-button.css:10:42
unreachable code after return statement[Saber más]  quicknote.js:869
El uso de eventos Mutation está desaprobado. Use en su lugar
MutationObserver.  calendar-widgets.xml:506:18
Propiedad desconocida '-moz-box-shadow'.  Declaración rechazada.
note.css:36:19
ColumnsWizard >>> 8:55:18.571
ColumnsWizard loaded...
2018-02-16 08:55:18.967 [SubjectManager.initializeOverlayStartup]:
Initialization has been completed
Error Parsing ICS: 2152333568 calIcsParser.js:139:25
ColumnsWizard >>> 8:55:46.226
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: espera
ColumnsWizard >>> 8:55:46.226
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: espera
ColumnsWizard >>> 8:55:46.226
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: espera
ColumnsWizard >>> 8:55:46.226
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: espera
ColumnsWizard >>> 8:55:46.226
miczColumnsWizard_MsgUtils.msgHdrGetTags: espera
unreachable code after return statement[Saber más]
jquery.tokeninput.js:470:4
file:///C:/Users/jporgar/AppData/Roaming/Thunderbird/Profiles/6070ojra.default/extensions/
messagenotesplus@mozilla.org/assets/icons/note_status_0.png
file:///C:/Users/jporgar/AppData/Roaming/Thunderbird/Profiles/6070ojra.default/extensions/
messagenotesplus@mozilla.org/assets/icons/note_status_0.png

2018-02-15 22:13 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-16 09:21
Is there nothing else after those lines?
I don't see the commands used with an IMAP server to set the flags and the labels.
Thank you.

**Comment by MemePortela** [comment] 2018-02-16 09:24
If I am checking that it works in the inbox and when it does not work it
is in the local folders.

2018-02-16 9:21 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-16 09:25
Ok, I'll check it. Thank you.

**Comment by MemePortela** [comment] 2018-02-16 11:42
Error in the inbox


          Se esperaba una declaración, pero se encontró '!'.  Ignorado
hasta la siguiente declaración.  quicknote-button.css:10:42
unreachable code after return statement[Saber más]  quicknote.js:869
El uso de eventos Mutation está desaprobado. Use en su lugar
MutationObserver.  calendar-widgets.xml:506:18
Propiedad desconocida '-moz-box-shadow'.  Declaración rechazada.
note.css:36:19
ColumnsWizard >>> 11:41:22.347
ColumnsWizard loaded...
2018-02-16 11:41:22.836 [SubjectManager.initializeOverlayStartup]:
Initialization has been completed
Error Parsing ICS: 2152333568 calIcsParser.js:139:25
ColumnsWizard >>> 11:41:33.362
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: error
ColumnsWizard >>> 11:41:33.362
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: error
ColumnsWizard >>> 11:41:33.362
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: error
ColumnsWizard >>> 11:41:33.362
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: error
ColumnsWizard >>> 11:41:33.362
miczColumnsWizard_MsgUtils.msgHdrGetTags: error

2018-02-16 9:25 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-16 11:45
"error" is the label name?
It worked in the inbox?

**Comment by MemePortela** [comment] 2018-02-16 11:48
NO, the label name is "Estado"
Yes in the inbox

2018-02-16 11:45 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-16 11:50
Are you using an addon to manage labels?

**Comment by MemePortela** [comment] 2018-02-16 11:52
The attached file show my addons

2018-02-16 11:50 GMT+00:00 Mic <notifications@github.com>:

**Comment by micz** [comment] 2018-02-16 14:42
There is no attachment.

**Comment by MemePortela** [comment] 2018-02-16 15:12
Can you see this down


Meme Portela
Enviado desde mi iPhone

**Comment by MemePortela** [comment] 2018-02-16 15:13
I attach but i can see in The email but not here

**Comment by micz** [comment] 2018-02-16 15:16
You have to post it directly on the github site, not via email.

**Comment by MemePortela** [comment] 2018-02-16 15:30
From mi phone not show how to attach. Only text

**Comment by MemePortela** [comment] 2018-02-16 15:32
Do you have a email where i can send you

**Comment by micz** [comment] 2018-02-16 15:36
m@micz.it Thank you

**Comment by MemePortela** [comment] 2018-02-19 12:18
![ashampoo_snap_2018 02 16_11h52m06s_005_](https://user-images.githubusercontent.com/32059442/36377384-eb034752-156e-11e8-8bbb-543e9f1a8f46.png)
Now I can!!!

**Comment by MemePortela** [comment] 2018-02-19 13:34
![ashampoo_snap_2018 02 16_11h52m06s_005_](https://user-images.githubusercontent.com/32059442/36377384-eb034752-156e-11e8-8bbb-543e9f1a8f46.png)
Now I can!!!

**Comment by micz** [comment] 2018-02-19 14:16
Why have you closed the issue? Is this problem fixed in the last beta version I released?
Thank you.

**Comment by MemePortela** [comment] 2018-02-19 14:35
No, I'm sorry, I speak Spanish and I have to translate into English, I have to touch the wrong button.

**Comment by micz** [comment] 2018-02-22 20:33
I tried everything on my test environment and it always works on IMAP or Local folders.
Also it's very strange the behavior that shows that "error" message on the labels list. That value is given by a native Thunderbird function, and I can't do anything about it.
I checked also your addons, but I can't tell if one of them is messing with labels.

The last thing is the log. In your log are missing these lines:

```
ColumnsWizard >>> 23:0:2.774
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags: $label2,nonjunk
ColumnsWizard >>> 23:0:4.378
miczColumnsWizard_MsgUtils.postActions miczColumnsWizard_MsgUtils.tags: $label2 nonjunk
```

And it shouldn't happen without an error message.

May you try my last alpha version without the other addons enabled?
I'm sorry I can't help you further without more information.

**Comment by davidhedlund** [comment] 2018-02-22 20:43
I think it would help if you give him the download link as you did for me.

**Comment by davidhedlund** [comment] 2018-02-22 20:46
@MemePortela You can find the alpha version micz refers to at https://addons.mozilla.org/en-US/thunderbird/addon/columnswizard/versions/beta

**Comment by davidhedlund** [comment] 2018-02-22 20:47
@MemePortela https://addons.mozilla.org/en-US/thunderbird/addon/columnswizard/versions/6.1alpha6 to be exact.

**Comment by MemePortela** [comment] 2018-02-23 10:33
Se esperaba una declaración, pero se encontró '!'.  Ignorado hasta la
siguiente declaración.  quicknote-button.css:10:42
unreachable code after return statement[Saber más]  quicknote.js:869
El uso de eventos Mutation está desaprobado. Use en su lugar
MutationObserver.  calendar-widgets.xml:506:18
Propiedad desconocida '-moz-box-shadow'.  Declaración rechazada.
note.css:36:19
ColumnsWizard >>> 10:29:28.434
ColumnsWizard loaded...
2018-02-23 10:29:28.876 [SubjectManager.initializeOverlayStartup]:
Initialization has been completed
Error Parsing ICS: 2152333568 calIcsParser.js:139:25
ColumnsWizard >>> 10:30:8.461
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: cedentes
ColumnsWizard >>> 10:30:8.461
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: cedentes
ColumnsWizard >>> 10:30:8.461
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: cedentes
ColumnsWizard >>> 10:30:8.461
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: cedentes
ColumnsWizard >>> 10:30:8.461
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags:
cedentes

2018-02-22 20:47 GMT+00:00 David Hedlund <notifications@github.com>:

**Comment by MemePortela** [comment] 2018-02-23 10:39
click in Error Parsing ICS: 2152333568 <(215)%20233-3568>
calIcsParser.js:139:25

DEPRECATION WARNING: The arguments you're passing to viewSource.xul are
using an out-of-date API.
You may find more details about this deprecation at:
https://developer.mozilla.org/en-US/Add-ons/Code_snippets/View_Source_for_XUL_Applications
chrome://global/content/viewSource.js 329 _loadViewSourceDeprecated
chrome://global/content/viewSource.js 309 onXULLoaded
chrome://global/content/viewSource.js 175 handleEvent


2018-02-23 10:33 GMT+00:00 Meme Portela <memeportela@gmail.com>:

**Comment by micz** [comment] 2018-02-25 14:37
I've released version 6.1alpha7, with more debug info.
You should now find something like that:

```
ColumnsWizard >>> 15:33:19.39
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: $label2 nonjunk
ColumnsWizard >>> 15:33:19.39
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: $label2,nonjunk
ColumnsWizard >>> 15:33:19.39
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags: $label2,nonjunk
ColumnsWizard >>> 15:33:20.282
miczColumnsWizard_MsgUtils.SetMessageKey START
ColumnsWizard >>> 15:33:20.282
miczColumnsWizard_MsgUtils.SetMessageKey IMAP
ColumnsWizard >>> 15:33:20.518
miczColumnsWizard_MsgUtils.folderListener.OnItemAdded START
ColumnsWizard >>> 15:33:20.518
miczColumnsWizard_MsgUtils.folderListener.OnItemAdded DOING POSTACTION
ColumnsWizard >>> 15:33:20.518
miczColumnsWizard_MsgUtils.postActions START
ColumnsWizard >>> 15:33:20.525
miczColumnsWizard_MsgUtils.postActions HDR DONE
ColumnsWizard >>> 15:33:20.525
miczColumnsWizard_MsgUtils.postActions SETTING LABELS
ColumnsWizard >>> 15:33:20.526
miczColumnsWizard_MsgUtils.postActions miczColumnsWizard_MsgUtils.tags: $label2 nonjunk
ColumnsWizard >>> 15:33:20.529
miczColumnsWizard_MsgUtils.postActions LABELS SET
```

Please try this version and post here the log from the error console.
Thank you.

**Comment by MemePortela** [comment] 2018-02-26 08:47
Se esperaba una declaración, pero se encontró '!'.  Ignorado hasta la
siguiente declaración.  quicknote-button.css:10:42
unreachable code after return statement[Saber más]  quicknote.js:869
El uso de eventos Mutation está desaprobado. Use en su lugar
MutationObserver.  calendar-widgets.xml:506:18
Propiedad desconocida '-moz-box-shadow'.  Declaración rechazada.
note.css:36:19
ColumnsWizard >>> 8:46:23.547
ColumnsWizard loaded...
2018-02-26 08:46:23.972 [SubjectManager.initializeOverlayStartup]:
Initialization has been completed
Error Parsing ICS: 2152333568 calIcsParser.js:139:25
1519634812867    addons.update-checker    WARN    Update manifest for
{972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1519634813114    addons.update-checker    WARN    Update manifest for
thunderbird-hotfix@mozilla.org did not contain an updates property
ColumnsWizard >>> 8:46:53.952
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: cedentes
ColumnsWizard >>> 8:46:53.952
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: cedentes
ColumnsWizard >>> 8:46:53.952
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags:
cedentes

2018-02-25 14:37 GMT+00:00 Mic <notifications@github.com>:

**Comment by MemePortela** [comment] 2018-02-26 08:54
The last email was for local folders
And this is for IMAP inbox

Se esperaba una declaración, pero se encontró '!'.  Ignorado hasta la
siguiente declaración.  quicknote-button.css:10:42
unreachable code after return statement[Saber más]  quicknote.js:869
El uso de eventos Mutation está desaprobado. Use en su lugar
MutationObserver.  calendar-widgets.xml:506:18
Propiedad desconocida '-moz-box-shadow'.  Declaración rechazada.
note.css:36:19
ColumnsWizard >>> 8:52:30.221
ColumnsWizard loaded...
2018-02-26 08:52:30.621 [SubjectManager.initializeOverlayStartup]:
Initialization has been completed
Error Parsing ICS: 2152333568 calIcsParser.js:139:25
ColumnsWizard >>> 8:52:39.596
miczColumnsWizard_MsgUtils.msgHdrGetTags keywords: cedentes
ColumnsWizard >>> 8:52:39.596
miczColumnsWizard_MsgUtils.msgHdrGetTags keywordList: cedentes
ColumnsWizard >>> 8:52:39.596
miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags:
cedentes

2018-02-26 8:47 GMT+00:00 Meme Portela <memeportela@gmail.com>:

**Comment by micz** [comment] 2018-02-26 08:56
Is there nothing in the log after the

`miczColumnsWizard_MsgUtils.init miczColumnsWizard_MsgUtils.msgHdrGetTags: cedentes`

line?

**Comment by MemePortela** [comment] 2018-02-26 08:58
No, I copy all lines

2018-02-26 8:56 GMT+00:00 Mic <notifications@github.com>:

**Comment by MemePortela** [comment] 2018-02-26 09:01
![ashampoo_snap_2018 02 26_09h00m23s_001_](https://user-images.githubusercontent.com/32059442/36661587-91b85a06-1ad3-11e8-8e0e-163d21922d6c.png)

**Comment by micz** [comment] 2018-02-26 21:37
This is really strange.
I've released version 6.1alpha8 with more logs, hopefully we should understand where is the problem.
May you try it and post the logs?
Thank you.

**Comment by MemePortela** [comment] 2018-02-27 08:29
Inbox --------------------------------------
![ashampoo_snap_2018 02 27_08h25m18s_001_](https://user-images.githubusercontent.com/32059442/36718036-425b6e7e-1b98-11e8-809b-0724dd83285d.png)

Local Folder -------------------------------
![ashampoo_snap_2018 02 27_08h26m32s_002_](https://user-images.githubusercontent.com/32059442/36718064-6087ead0-1b98-11e8-8a46-c7a24294060f.png)

**Comment by micz** [comment] 2018-02-27 22:13
From the logs everything seems correct. I'm sorry I really can't understand what's happening on your system.
Have you tried this without any other addon?
Thank you for your patience.

**Comment by micz** [comment] 2018-03-12 20:25
I'm closing this issue. I'm sorry I wasn't able to replicate the problem.
I'm going to release version 6.1. Once released, if you find new information about this problem and need more help, feel free to open a new issue.

**Closed by micz** 2018-03-12 20:25 UTC
Labels: bug
