### ISSUE TITLE
Merge Header Tools Lite to ColumnsWizard

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#28] opened 2015-05-22 01:43 UTC
![screenshot from 2015-05-22 02 42 33](https://cloud.githubusercontent.com/assets/6416073/7762881/1e39c432-0039-11e5-8141-5e385468c5ec.png)

![screenshot from 2015-05-22 04 19 05](https://cloud.githubusercontent.com/assets/6416073/7763063/baa3f156-003b-11e5-943e-8974ceb65657.png)

@micz To make use of ColumnsWizard for customized columns you must use additional add-ons like Header Tools Lite to add data. This is how I added "Category" as seen on the first screenshot and "xsubject on the second screenshot.

* With ColumnsWizard 5.0.2, create this entry: ID: xsubject, Mail header: xsubject, Column Name: Category, Tooltip: Edit with Header Tools Lite.
* Add “Category” from the column context menu.
* With Header Tools Lite: Modify Header Tools Lite by adding xsubject (ask me if you want a copy).
* Restart Thunderbird and add a category to a mail by going to: Email context menu -> Header Tools Lite -> Change header details.

The problem is that you have to modify Header Tools Lite each time you add a new header with ColumnsWizard, this step would not be needed at all if they were merged.

The SSL of Header Tools Lite homepage, https://nic-nac-project.org/~kaosmos/headertoolslite-en.html, have expired. The add-on have not been updated in over one year. I emailed the author the link to this Issue (email seen in screenshot 2).

Can you please consider merging Header Tools Lite to ColumnsWizard?

**Comment by micz** [comment] 2015-05-23 06:00
The idea of CW is to show an already present mail header.
What you're asking is a way to add and manually modify a custom header on a single mail message.

I think merging that addon could yield to make CW very less usable.

Maybe a better solution could be to add an "advanced" tab on the custom header form that lets the user define that header as "manually modifiable".
For those "modifiable" custom headers I could add a context menu, like header tools does, to modify it.
In this way an user could even define how to modify it, as free text, a fixed list....

What do you think about it?

**Comment by davidhedlund** [comment] 2015-05-23 14:18
@micz Can you please give me a modified screenshot of your idea?

**Comment by micz** [comment] 2015-05-29 20:59
In the Custom Colum Editor, something like that:
![mockup_ui_issue28](https://cloud.githubusercontent.com/assets/61795/7892605/214c226e-0656-11e5-9f8d-16302b603045.png)

Then, in the message list, adding a menu item that let the user modify those headers (opening an editor if number or free text, or directly choosing from the menu if a fixed list).

I hope it's more clear now.

**Comment by davidhedlund** [comment] 2015-05-29 21:54
@micz Thank you for taking your time. I think that is what I'm talking about. Do you want to implement it? =)

**Comment by micz** [comment] 2015-05-29 22:09
I think it's a good idea and I'll take into account for future development.
Thank you!

**Comment by davidhedlund** [comment] 2015-05-30 00:25
@micz Namaste.

**Comment by micz** [comment] 2015-08-18 09:58
Working on branch headermod: https://github.com/micz/ColumnsWizard/tree/headermod

**Comment by davidhedlund** [comment] 2015-08-18 10:29
@micz I'm excited.

**Comment by micz** [comment] 2015-08-21 14:27
May you test this version?
https://www.dropbox.com/s/vc49uze6i9kez9f/ColumnsWizard-headermod.xpi?dl=0

Please consider that not all the development for 5.2 (https://github.com/micz/ColumnsWizard/milestones/5.2) has been done in this branch.
Some new feature and bug fixes not related to this issue have been pushed directly to trunc.
Consider also this still open bug: #40.

Thanks.

**Comment by micz** [comment] 2015-08-21 20:07
I've updated the file link in the previous comment, please use this new one. Thanks.

**Comment by micz** [comment] 2015-08-22 08:57
New version released. Link updated in the previous post.

**Comment by davidhedlund** [comment] 2015-08-25 02:28
@micz I will try version 6.0 once it gets updated automatically in Icedove. That is, when its uploaded and signed in addons.mozilla.org as the latest release.

Thank you for your hard work so far micz.

**Comment by micz** [comment] 2015-08-25 19:32
This feature will be released in version 6.0.
Version 5.2 is for some other minor features and fixes and I decided to release those alone.

I used some Header Tools Lite code as stated in the source code, here: https://github.com/micz/ColumnsWizard/blob/headermod/chrome/content/mzcw-msgutils.jsm

Before releasing it on AMO I need a little help in testing. It could be possibile for you to test it if I release it on AMO in the beta channel?
Otherwise I'll look for someone else to test it.

I'll add your name in the release notes when describing this new feature.

**Comment by davidhedlund** [comment] 2015-08-25 19:38
@micz Thank you. Please also mention Header Tools Lite in the release notes.

I can beta-test version 6.0 for you but it seems like its not available for download yet. Please let me know where and when I can get it.

**Comment by micz** [comment] 2015-08-25 19:40
Ok, thanks. I'll write here when ready.
I'll release it in the next few days.

**Comment by micz** [comment] 2015-09-10 21:10
I added the new version in the beta channel, sorry for the delay.
You could download it from here: https://addons.mozilla.org/en-US/thunderbird/addon/columnswizard/versions/beta

I wait for your feedback. Thanks!

**Comment by davidhedlund** [comment] 2015-09-11 15:34
Thank you too. I'll try it in a fresh Icedove profile for evaluation next week most likely. Have a nice weekend @micz.

**Comment by davidhedlund** [comment] 2015-09-15 00:08
@micz In the "Advanced" tab I've selected "This mail message header can be manually modified". I choosed "Free text". Where do I change it now?

**Comment by micz** [comment] 2015-09-15 19:25
Great!

I think I won't add a multiple message headers editor, since it's something not on topic for this addon.
For the shortcut I've raised the issue #43.

For the sort problems, I need some info, since on my system I can't reproduce it:
 * Thunderbird version
 * Account type (POP3 / IMAP)
 * Which mail header are you modifying.

Thanks.

**Comment by davidhedlund** [comment] 2015-09-15 22:53
Why are you not interested to add a multiple header editor?

* Icedove 31.8.0
* Account type: SMTP
* Any modified mail header will break the previous sort.

**Comment by micz** [comment] 2015-09-16 22:12
I tested it in a Debian virtual machine with Icedove 31.8.0 and it works.
When changing an header it changes the listed message and then it sorts the messages list immediately.
I still can't reproduce the bug.
May you send me the installed addon list? If you don't want to publish it here, send it to m@micz.it.
Thanks.

**Comment by davidhedlund** [comment] 2015-09-16 23:37
@micz It works as long as I sort by the header that is being edited, but not if I sort by date and then edit.

No add-ons installed except CW.

**Comment by davidhedlund** [comment] 2015-09-16 23:49
@micz I rewarded you with a link to gratis italodisco!

**Comment by micz** [comment] 2015-09-21 20:11
Thanks for the test.
I'm going to release version 6.0 in the next days.

**Comment by davidhedlund** [comment] 2015-09-22 05:21
@micz This is a great milestone to the the Icedove community. I will upgrade ASAP. All the best.

**Comment by davidhedlund** [comment] 2015-09-22 05:25
@micz Please add the new feature to the text in:
* https://addons.mozilla.org/thunderbird/addon/columnswizard/
* http://micz.it/thunderdbird-addon-columnswizard/

**Closed** 2015-09-22 20:49 UTC
Labels: new feature

**Comment by davidhedlund** [comment] 2015-09-24 11:25
@micz Please let me know when its is uploaded on addons.mozilla.org.

**Comment by micz** [comment] 2015-09-24 18:39
I'm currenlty waiting for the translators to update their languages.
I'll wait till next week before updating.

**Comment by micz** [comment] 2015-09-30 20:20
Version 6.0 has been released today.

**Comment by davidhedlund** [comment] 2015-10-02 09:14
@micz Thanks! I just updated CW to version 6.0 but could not find any shortcuts. Have you added them?

**Comment by micz** [comment] 2015-10-02 12:34
The shortcuts will be added in a next version: #43.
